on:
  push:
    tags:
      - '*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v1
      - name: build
        id: build_ipk
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
          mkdir -p /tmp/luci-app-esurfing-client/usr/lib/lua/luci /tmp/luci-app-esurfing-client/usr/bin/esurfing-client
          [ -d $GITHUB_WORKSPACE/luasrc ] && cp -R $GITHUB_WORKSPACE/luasrc/* /tmp/luci-app-esurfing-client/usr/lib/lua/luci/
          [ -d $GITHUB_WORKSPACE/root ] && cp -R $GITHUB_WORKSPACE/root/* /tmp/luci-app-esurfing-client/
          chmod +x /tmp/luci-app-esurfing-client/etc/init.d/* >/dev/null 2>&1
          chmod +x /tmp/luci-app-esurfing-client/etc/uci-defaults/* >/dev/null 2>&1
          [ -d $GITHUB_WORKSPACE/po ] && sudo -E apt-get -y install gcc make && \
          mkdir -p /tmp/po2lmo && mkdir -p /tmp/luci-app-esurfing-client/usr/lib/lua/luci/i18n/ && \
          wget -O /tmp/po2lmo/po2lmo.c https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/po2lmo.c && \
          wget -O /tmp/po2lmo/Makefile https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/Makefile && \
          wget -O /tmp/po2lmo/template_lmo.h https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.h && \
          wget -O /tmp/po2lmo/template_lmo.c https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.c && \
          cd /tmp/po2lmo && make po2lmo && ./po2lmo $GITHUB_WORKSPACE/po/zh-cn/esurfing-client.po /tmp/luci-app-esurfing-client/usr/lib/lua/luci/i18n/esurfing-client.zh-cn.lmo
          mkdir -p /tmp/luci-app-esurfing-client/CONTROL
          cat >/tmp/luci-app-esurfing-client/CONTROL/control <<EOF
          Package: luci-app-esurfing-client
          Version: ${TAG}
          Depends: luci-base, luarocks
          Architecture: all
          Maintainer: LengSword<https://github.com/LengSword/luci-app-esurfing-client>
          Section: luci
          Priority: optional
          Description: LuCI app for China Telecom's esurfing school client
          Source: https://github.com/LengSword/luci-app-esurfing-client
          EOF
          cat >/tmp/luci-app-esurfing-client/CONTROL/postinst <<EOF
          #!/bin/sh
          if [ -z "${IPKG_INSTROOT}" ]; then
          ( . /etc/uci-defaults/40_luci-esurfing-client ) && rm -f /etc/uci-defaults/40_luci-esurfing-client
          fi
          exit 0
          EOF
          chmod +x /tmp/luci-app-esurfing-client/CONTROL/postinst
          wget -O /tmp/ipkg-build https://raw.githubusercontent.com/openwrt/openwrt/openwrt-18.06/scripts/ipkg-build && \
          chmod +x /tmp/ipkg-build && \
          /tmp/ipkg-build -o root -g root /tmp/luci-app-esurfing-client /tmp
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: /tmp/luci-app-esurfing-client_${{ steps.build_ipk.outputs.tag_name }}_all.ipk
          asset_name: luci-app-esurfing-client_${{ steps.build_ipk.outputs.tag_name }}_all.ipk
          asset_content_type: application/octet-stream
